### PR TITLE
V4 -- Update for template v2.0.1-5

### PR DESCRIPTION
**Pull request by stylesuxx**
Primarly needed to update the way, the postcss related stuff is attached since it is attached to the webpack config, which has changed.

### CODE REVIEW

**Comment by sthzg** [comment]
@stylesuxx changes are looking good. does this fix the PostCSS part completely (from the template side)? Then I'd merge and publish the next pre-release. Otherwise I'd merge and wait a little before publishing.

**Comment by stylesuxx** [comment]
I have not tested the postcss part yet, but I can do that in the evening and report back - if I did not completely mess up the webpack config it should still be working - at least the tests pass regarding the attachment of the postcss functionality. I remember you mentioned that something was not working properly - can you link me to an issue?

**Comment by sthzg** [comment]
That is a good question. AFAIK in the V4 app generator the PostCSS part was reported to be buggy. I couldn't find a Github issue, but [this comment](https://github.com/react-webpack-generators/generator-react-webpack/blob/master/generators/app/index.js#L157-L161) serves as an indicator that there were problems. Maybe @weblogixx still has a bit of context on that. Otherwise I will also test a setup and see what it does/does not do.

I will merge this to 2.x now so that it can be tested against the template w/ the necessary modifications in this PR.

**Comment by sthzg** [comment]
FYI: I tested an installation w/ PostCSS enabled and filed an error on this issue #307.

**Pull request merged**
